# Sales Records Analysis

### Author: Kevin Tran

### Exercise 2.E Using functions for analyzing data

This notebook analyzes a small sales dataset using python functions.
Each function takes the full dataset as its first argument.

In [32]:
sales_data = [
    ('Laptop',    'East',  1200.00),
    ('Phone',     'West',  850.00),
    ('Tablet',    'East',  400.00),
    ('Monitor',   'South', 650.00),
    ('Keyboard',  'West',  75.00),
    ('Laptop',    'South', 1150.00),
    ('Phone',     'East',  900.00),
    ('Tablet',    'West',  425.00),
    ('Monitor',   'East',  680.00),
    ('Keyboard',  'South', 80.00),
    ('Laptop',    'West',  1300.00),
    ('Phone',     'West',  820.00)
]

## Lab 1. Total sales by region

In [33]:
def region_total(data, region):
    return sum(amt for _, reg, amt in data if reg == region)

In [34]:
print(region_total(sales_data, 'East'))
print(region_total(sales_data, 'West'))
print(region_total(sales_data, 'South'))

3180.0
3470.0
1880.0


## Lab 2. Count of sales by region

In [35]:
def region_count(data, region):
    return sum(1 for _, reg, amt in data if reg == region)

In [36]:
print(region_count(sales_data, 'East'))
print(region_count(sales_data, 'West'))
print(region_count(sales_data, 'South'))

4
5
3


## Lab 3. Average sale amount by region

In [37]:
def region_average(data, region):
    count = region_count(data, region)

    if count == 0:
        return 0

    return region_total(data, region) / count



In [38]:
print(region_average(sales_data, "East"))
print(region_average(sales_data, "West"))
print(region_average(sales_data, "South"))
print(region_average(sales_data, "North"))

795.0
694.0
626.6666666666666
0


## Lab 4. Filter by sale amount

In [39]:
def sales_above(data, threshold):
    return [record for record in data if record[2] > threshold]


In [40]:
results = sales_above(sales_data, 500)

for record in results:
    print(record)

('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Monitor', 'South', 650.0)
('Laptop', 'South', 1150.0)
('Phone', 'East', 900.0)
('Monitor', 'East', 680.0)
('Laptop', 'West', 1300.0)
('Phone', 'West', 820.0)


#### BONUS

In [41]:
def sales_below(data, threshold):
    return [record for record in data if record[2] < threshold]

In [42]:
results = sales_below(sales_data, 500)

for record in results:
    print(record)

('Tablet', 'East', 400.0)
('Keyboard', 'West', 75.0)
('Tablet', 'West', 425.0)
('Keyboard', 'South', 80.0)


## Lab 5. Top and bottom sale

In [46]:
def top_sale(data):
    return max(data, key=lambda record: record[2])

print(top_sale(sales_data))

('Laptop', 'West', 1300.0)


In [47]:
def bottom_sale(data):
    return min(data, key=lambda record: record[2])

print(bottom_sale(sales_data))

('Keyboard', 'West', 75.0)


The top sale was a laptop in the West Region for $1300.00

The bottom sale was a keyboard in the West region for $75.00

## Lab 6. Apply a discount